DROP TABLE IF EXISTS dogs;
DROP TABLE IF EXISTS users;

CREATE TABLE dogs (
    dog_id INT NOT NULL,
    name VARCHAR(250) NOT NULL,
    age INT NOT NULL
);


CREATE TABLE TEST AS SELECT * FROM CSV-READ('db-bonds-data.csv');

CREATE TABLE users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(250) NOT NULL,
    password VARCHAR(250) NOT NULL
);


